### ISSUE TITLE
Add indexing of the language code

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#369]
Not sure why Paakantyi (drl) is missing from the language list. http://www.ethnologue.com/language/drl Could there be a way for admins to insert a language code ?

**Comment by agrimmtt** [comment]
@nthieberger On staging, if you edit http://144.6.225.96/collections/AA1/items/001 you can use codes as well as the name when looking for a country or subject or content language. This will be available in production on the next deploy.

@jangari You subsequently created ticket #390 for that, which has since been resolved.
