### ISSUE TITLE
Delete items and collections

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#375]
We need the ability to delete collections even if they have content, and also to delete items if they have content. At the moment we need to delete each essence file before we can delete an item and each item before we can delete a collection.

**Comment by jangari** [comment]
Just to confirm, the desired behaviour for items (when hitting 'delete item' button) is:

1. Check if there are dependent essence files.
2. If dependent files, inform user that this item has dependent essence files, and deleting the item will permanently delete all essence files. This cannot be undone.
3. Ask 'Do you want to proceed?'
4. If yes, delete all dependent essence files and the item.
5. If there are no dependent essence files, warn that this cannot be undone. 
6. Do it.

**Comment by nthieberger** [comment]
Yes, as an example, a depositor has provided metadata that I have imported (EG1) and then rethought the structure of the collection so that all existing items need to be deleted and replaced with new items (with different names). There are 140 of them so we don't want to be doing that item-by-item.

**Comment by stasb** [comment]
Hi, has this issue now been resolved?

**Comment by nthieberger** [comment]
I successfully deleted EG1 from the catalog, but the EG1 items are now in the collection without a catalog references, that is , the deletion did not affect them (unless there is a time lag between the operation in NABU and the actual filesystem perhaps?). They were meant to be deleted together withthe catalog entries.

**Comment by stasb** [comment]
Fixed this so that a collection won't be deleted if any items still remain. Appropriate messages will now also show that indicate why an item or essence could not be deleted (flash messages were often not showing).

In my testing I was able to delete most collections. There were occasional errors with deleting essences and removing files, which then prevented items and their parent collection from being deleted.

Please test once live and let me know if the deleting behaviour is correct. Might have to change it so we can force delete collections/items if there is something blocking the removal process.

**Comment by nthieberger** [comment]
I just tested this and deleted the DL1 collection, which seems to have worked in the staging server without any warnings, but maybe because there are no files to block the deletion?

**Comment by nthieberger** [comment]
And we still need to delete the contents of the collection EG1 which is no longer in the catalog but is still in the filesystem.

**Comment by AmandaPDSC** [comment]
have copied outstanding issue to #417
