### ISSUE TITLE
Use Creative Commons 

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#389]
Add a CC licence (Attribution-Share Alike CC BY-SA) to the bottom of each collection and item entry, also at the bottom of the home page. This licence covers use of the catalog information.

**Comment by nthieberger** [comment]
Yes, perhaps. And it should also say 'The moral rights of the performers are asserted'

**Comment by JonoGillett** [comment]
Since the collection page doesn't have the "cite as" field, I think it would be most consistent to do what many other pages do and have the license as part of the footer.

Doing so ends up looking like this, using the CC licence builder tool:
![image](https://cloud.githubusercontent.com/assets/10914573/7016994/aeafd8d6-dd33-11e4-84cb-9a5c17000d4e.png)

How do you feel about that, or would you like me to put it more in with the other fields?

**Comment by nthieberger** [comment]
That looks fine as a footer, thanks.

**Comment by stasb** [comment]
Hi, has this issue now been resolved?
