### ISSUE TITLE
Writing to the collection does not occur when a spreadsheet import is done

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#399]
If a collection is added via a spreadsheet import, the relevant CAT-PDSC_ADMIN.xml files are not generated unless each individual item is opened and saved. It would be preferable if each item was written to the xml file on import of the spreadhseet.

**Comment by nthieberger** [comment]
A further problem - I can't upload a spreadsheet with me as collector, it says I do not exist as a user. And, another issues, the prompt on this page "http://catalog.paradisec.org.au/collections/spreadsheet" says upload XSL page but it should say XLS.

**Comment by nthieberger** [comment]
Just replicated this with Alan Walker as the collector. He is listed in AW2, but the spreadsheet import fails.

**Comment by JonoGillett** [comment]
Regarding the original post and the XSL/XLS typo - those are pretty straightforward to fix.

Regarding the "unable to find user" issue:
I think this is due to the way the name parsing in the spreadsheet upload works. It's possibly a bug or oversight - it expects names to be in the form "First, Last" <- note the comma.

Since you probably just wrote "First Last" it interpreted that as "First Last, <nothing>" and couldn't find you.

We have a few options here:
- We can force users to enter the name in a certain format (e.g. "Last, First" or "First, Last")
- We can have separate first and last name fields in the spreadsheet upload to avoid the problem entirely
  - However I don't know if it's inconvenient for your existing uploaders etc to change over to a different form
- We can have the spreadsheet check multiple different formats (this is the harder and usually less accurate option)

My preference, since it is guaranteed to give us the correct data, is to have 2 fields instead of one. What do you think?

**Comment by nthieberger** [comment]
No, it doesn't matter what form the collector's name is in, it still fails to import 

"Please create user Walker, Alan first
ERROR collector does not exist"

There is a problem with spreadsheet import more generally.

**Comment by JonoGillett** [comment]
Nick, sorry to be pedantic, but could you try "Alan, Walker" (First name <comma> Last name) and see if that works?
I'm pretty confident it's the name format that is the problem based on the log output.

**Comment by nthieberger** [comment]
It used to work! With the name as first last. I tried your suggestion, but it just generated an error.

**Comment by JonoGillett** [comment]
I think I see when the problem began: https://github.com/nabu-catalog/nabu/issues/392
It looks like to fix the multi-part name problem the name format of "First names, Last names" was enforced.

I'll take a look and see if I can work out why you're getting the error though. I am able to upload a spreadsheet successfully.

**Comment by nthieberger** [comment]
that worked. I think there could be an issue around empty fields throwing
an error?
