### ISSUE TITLE
Checksums

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#412]
Build a checksum system into the collection, from first ingestion and then through transport, then store checksums with objects and amend them when a file has been processed (e.g. sealed with BWF).

**Comment by nthieberger** [comment]
I'm not sure how to implement this. It needs a system for generating checksums at ingestion (which could be in Melbourne or Canberra) and checking them after the file is sent to the 'from' folders on the server called Azoulay, I'm not sure if Terem has access to that server. The files are then changed by the ingestion process so a new checksum should be generated after sealing as a BWF and that should then be stored and used for any quality assurance checking of the collection.

**Comment by silviapfeiffer** [comment]
Remember how we created a means to add all sorts of admin files to a repository without it showing up in the catalog? This is another such file type. Of you name the file correctly and put it in the right folder on azoulay next to the media files, it will just get copoed into the archive, too.

**Comment by nthieberger** [comment]
Yes, of course. So we store them with the same name as the file so e.g., RT1-001-A.wav would have a corresponding file something like RT1-001-A-CS-PDSC_ADMIN.txt . This would then be overwritten only when the file was legitimately changed (by being sealed as BWF). We need to generate these at the source ingestion station and then store them together with the essence file.

**Comment by jangari** [comment]
Since last year, I have been recording checksums of files as they are written onto Azoulay from Dobbin (so, immediately post-sealing), one checksum file per object, with each essence file (wav and mp3) stored within it. The system doesn't currently check non-audio files, but that could easily be incorporated into the script.

The file currently looks like this:

TS1-N047-1.md5
```
3a24a9ff7c790191ea70d105abec2d0d  TS1-N047-1.wav
c7dddcd7af226122404f670f37d5cbc1  TS1-N047-1.mp3
```

In which case, all I would need to do to have these files ingested along with their correspondent audio files and placed, invisibly, in the same directory, would be to change the filenames to something like what Nick suggested above, and we'll be a step closer to having good checksum capability. 

I suppose then it would be a good idea to have some verification method whereby the user can check any given essence file against the checksum stored in the text file and display the result.

**Comment by jangari** [comment]
@nthieberger, if you like I can globally change all existing checksum files and move them so as to be archived.

**Comment by nthieberger** [comment]
Yes, that would be good. We do need to be clear about the status of the checksum so that we don't store those that are for pre-sealed audio for example. We will only generate checksums at two places, source and Azoulay and the latter will overwrite the former so that should all be ok. But we need to develop a process for generating checksums at the source in Melbourne and Canberra (and Sydney)

**Comment by jangari** [comment]
Checksums at ingest into workflow definitely needed, and for files that undergo modifications (wav only, really), the ability to overwrite the existing checksum.

Ordinarily one wouldn't want to allow checksums to be overwritten by anything, but in this instance it's a necessity. I will have to think about how we allow wav file checksums to be overwritten, but then restrict that only to that point in the workflow when the wav file is sealed.

**Comment by jangari** [comment]
I'm going to name these [coll]-[item]-[object]-checksum-PDSC_ADMIN.txt, and I'm about to test the upload with TS1-N075-C.

**Comment by jangari** [comment]
I successfully uploaded the checksum file and, just for the hell of it, tested the corresponding audio files against their checksums. Unsurprisingly, they passed:

```
$ md5sum -c TS1-N075-C-checksum-PDSC_ADMIN.txt
TS1-N075-C.wav: OK
TS1-N075-C.mp3: OK
```

I suppose we have to figure out how to utilise these checksum files. Should we check the integrity of files automatically on ingestion? If we have checksums included as part of the workflow all the way through then it would be an excellent way to verify that what's been archived is identical to what was supplied by the depositor. Perhaps job no. 1 should be to create the checksum txt files when files are received, and perhaps we should encourage depositors of digital files to generate checksums on their end to verify with ours.

We could also display the checksums for a given file on its download page, as is common practice in software distribution, for example, so that the downloader can verify that the file they have is accurate.

**Comment by LindaBarwick** [comment]
Good for you Aidan. Can you please update Trello?

Professor Linda Barwick
Associate Dean (Research)
Sydney Conservatorium of Music
Greenway Building C41
The University of Sydney NSW 2006
T +61 (0)2 9351 1383 M +61 (0)409 712 722
E Linda.Barwick@sydney.edu.au
W sydney.edu.au/music

**Comment by jangari** [comment]
One method to utilise the checksums would be to modify every workflow script with a chunk that checks the file against its hash and only proceeds if it checks out. Dobbin would of course modify the file, so we'll simply regenerate a new one then. And also keep the checksum with the file, and upload it to the repository with the file.
