### ISSUE TITLE
map doesn't appear in some items

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#413]
A question. The map doesn't appear on some items, I'm note sure why:
http://catalog.paradisec.org.au/collections/NK3/items/MD008
http://catalog.paradisec.org.au/collections/NK3/items/MD012
http://catalog.paradisec.org.au/collections/NK3/items/MD013

It is there on other items in this collection:
http://catalog.paradisec.org.au/collections/NK3/items/MD011
http://catalog.paradisec.org.au/collections/NK3/items/MD014

**Comment by silviapfeiffer** [comment]
Probably when they were created, the author didn't set the map.
I've just edited http://catalog.paradisec.org.au/collections/NK3/items/MD008 and clicked on "Set map from language" and it sets it just fine. I was able to store it.

**Comment by silviapfeiffer** [comment]
Probably when they were created, the author didn't set the map.
I've just edited http://catalog.paradisec.org.au/collections/NK3/items/MD008 and clicked on "Set map from language" and it sets it just fine. I was able to store it.
(Couldn't resist. :-)

**Comment by nthieberger** [comment]
Thanks. So the issue is that the map should always appear, regardless of
whether the location has been entered. This jogs the user's memory about
it, and allows them also to draw a bounding box that is neither the
language nor the country.

**Comment by AmandaPDSC** [comment]
#453 is also about maps

**Comment by agrimmtt** [comment]
Hi @nthieberger and @AmandaPDSC . I've fixed an error in the website's code. It was trying to highlight in red "No map data given - please add." when there's no map, but wasn't doing so. I've fixed the code so that it's now in red.

Attached is a screenshot of the message highlighted in red. You can also see it on the staging machine if you desire.

Is this an acceptable way of highlighting the problem of a map not being set?

![screen shot 2015-09-17 at 12 04 11 pm](https://cloud.githubusercontent.com/assets/13618655/9923195/5c805eaa-5d35-11e5-88c3-ea6ca52b31d9.png)

**Comment by nthieberger** [comment]
Yep that works.
