### ISSUE TITLE
Operators are not collectors

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#434]
It looks like the operator in this collection is being treated as a collector. http://catalog.paradisec.org.au/collections/NK3

It comes up as one of my collections although I was only the operator

**Comment by JonoGillett** [comment]
It looks like this has been the case since the beginning (or at least since 2012).
The dashboard page explicitly checks for collections that you are a collector OR operator on, and displays those in your "My Collections" list.

Is this something you would like to change? It seems like it was done deliberately.

**Comment by nthieberger** [comment]
Yes, it needs to change. It represents operators (who are responsible for accessioning the collection into PARADISEC) as collectors, so presents them on the map and lists them in the citation form. They should not be listed in either of these places.

**Comment by JonoGillett** [comment]
Could you send me a link where you are seeing an operator listed in the citation?
I've tried a few different tests and couldn't reproduce that behaviour.

I'm looking at the Item view page, where it has "Cite As". Whatever values I enter for collector and operator, the only one to show up is the collector. Is this what you were referring to, or am I looking in the wrong place?

**Comment by nthieberger** [comment]
You are right, it all looks ok so let's close this one.
