### ISSUE TITLE
Visibility of access information on Nabu

### ISSUE THREAD

**Issue by juliamiller** [nabu-catalog/nabu#435]
ACCESS INFORMATION such as "Data access conditions" and "Data access details" are not visible to a basic user or a not-signed-in "catalog surfer", only admin (or perhaps those with edit rights for a collection). We should have access information visible to all, even those not yet signed in/up. This should include both the COLLECTION level and ITEM level.

As it stands, COLLECTION level access information is located in the info box "Access information" under the map. At the ITEM level, access information is in the "Admin information", not visible to most users, unless they have edit privileges. ITEM level access conditions should be moved into its own Access Information box, as it is with the COLLECTION level access, and made visible to default browsers, not just to those signed in.

**Comment by nthieberger** [comment]
This could be simplified by having a green icon that says 'open' next to an item, or red and 'closed', based on the contents of the 'access condition' field. This for each of the collection and item level.

**Comment by JonoGillett** [comment]
So i've pulled the access conditions out into an always-visible section named "Access Conditions" on both collections and items.

However I wasn't sure how to proceed with the icons - there are a few possible ways to flag items and collections, but it depends on the intended use. Mostly once you're on the page for a collection or item, it is visible whether you are able to do anything with it.

So in my mind the main place it would be beneficial would be in search results, so that in passing you can see what you are able to interact with. But I just don't know how that would be used.

@nthieberger how were you thinking these icons could be used? Am I overthinking it here, and what you really intended was just a more visually obvious indicator than the text version in this field?

**Comment by nthieberger** [comment]
In the 'items' list within a collection, there could be a green or red icon between the  item name and the title. This would allow a user to know what was available.

**Comment by JonoGillett** [comment]
A version of this is on staging at the moment, could you take a look and see if that's what you had in mind?
http://144.6.225.96/collections/TESTCI1
The top 3 items have "Open...", "Closed..." and "Mixed..." set on them, but the rest have not been set.
You can also hover over the icon to see the full access condition text.

**Comment by nthieberger** [comment]
This looks very good thanks. Would it be possible that the hover text includes the info from the field 'Data access narrative' if there is something there?

**Comment by juliamiller** [comment]
Hi,
For some reason, despite using my admin log in, I cannot see the collection you have linked to.

Cheers,
Julia

**Comment by JonoGillett** [comment]
Hmm that's very strange... There aren't any error messages in the logs, but I can definitely see you being redirected to the home page as usually happens when you get denied access.

Can you see the Admin option at the very bottom of the page? This will tell us whether other parts of the system recognise your admin account, even if that page doesn't.

Likewise, can you get to other collections using the admin power, for example: http://144.6.225.96/collections/AA2 (private and closed - should only be admin accessible)

**Comment by juliamiller** [comment]
I tried with this new link. Same messages: 


![nabu-001](https://cloud.githubusercontent.com/assets/10249439/8000226/24471fc4-0b9b-11e5-9f4a-c75bf6ae29a5.JPG)
![nabu-002](https://cloud.githubusercontent.com/assets/10249439/8000225/2444dcc8-0b9b-11e5-99ea-a024b1521cc6.JPG)

I tried to navigate to that collection whilst logged in as admin in another browser tab. No joy.
I can log in as admin fine, just not with the 114.6.225.96 bit. I expect this is your dev site?

**Comment by nthieberger** [comment]
Julia,
It could be that you are not authorised as an admin in the test server, sorry. But this is what the buttons look like:
(https://cloud.githubusercontent.com/assets/611488/8000419/b0f0633e-0b9d-11e5-9390-ebe1784dc12e.jpg)

**Comment by juliamiller** [comment]
Hi Nick,
Ah, yes, that is likely the case.
I do like the buttons.

Thanks.
Julia

**Comment by JonoGillett** [comment]
I have added the access narrative underneath the access condition in the tooltip, where it is set. It will appear like:
"Open (Subject to....  )

narrative goes here"

Is there anything else, or is this ticket ready to go at this point?

**Comment by nthieberger** [comment]
Well, that narrative should only appear if it has content and should be blank otherwise

**Comment by JonoGillett** [comment]
Sorry for not making it clearer but that's what I meant by "where it is set". If there is no narrative, it will simply show the condition on its own with no unnecessary space

**Comment by juliamiller** [comment]
Thanks. This looks great!

**Comment by AmandaPDSC** [comment]
The access conditions being displayed in the list of items in a collection seem to display the access conditions for the whole collection. So in DT1 10 items are closed but the other 575 are open. However, the next to each item in the list is the label "other" when it should show "open" for most items, and "closed" for some

**Comment by agrimmtt** [comment]
Hi @AmandaPDSC ,

Can you refer me to a DT1 item that should be showing "open", and an item that should be showing "closed"?

**Comment by AmandaPDSC** [comment]
sorry DT1 was a typo, it should have been DD1. DD1-001 is open, and DD1-166 is closed

**Comment by agrimmtt** [comment]
Hi @AmandaPDSC ,

This has been fixed, and is now awaiting deployment. You can see the fix on the staging machine at http://144.6.225.96/collections/DD1?items_per_page=343.

The bug was caused by changes made while adding access condition information to citations, as part of DOI minting work (https://github.com/nabu-catalog/nabu/issues/379#issuecomment-212751327). Sorry about that.
