### ISSUE TITLE
Wildcard search?

### ISSUE THREAD

**Issue by AmandaPDSC** [nabu-catalog/nabu#448]
There is currently no way to search for items that have been digitised - so maybe I want to find all of the items in AC2 that are digitised (or all of those that aren't). We used to have a digitised yes/no tick box, but now there is only a date digitised field. To find any items with a date digitised we might need to have a wildcard search for that field (and others).

This speaks to a larger issue of limits on search capability in Nabu - it would be great to be able to invert searches, remove some items from a search, add two searches together etc. Referenced in the thread for #106

**Comment by JonoGillett** [comment]
It sounds like this could be worth expanding to maybe a discussion about how you'd like to search. Personally the current advanced search is a bit overwhelming. There are other alternatives such as query builders, rather than having all fields all the time you just add criteria as you want them.

**Comment by JonoGillett** [comment]
As an example of what I mean, googling "javascript query builder ui" returned this: http://mistic100.github.io/jQuery-QueryBuilder/

There are plenty of other ones like that out there, and they all behave pretty similarly. Essentially you add an arbitrary number of criteria (field, operator, value -> e.g. "collector name", contains, "jono") and combine them or group them using boolean logic (and, or, not).

**Comment by AmandaPDSC** [comment]
It looks like a query builder would enable the kinds of searches we want to do (see details in #106 ) - what do you think @nthieberger ?

**Comment by JonoGillett** [comment]
Related to: #266 - perhaps both these issues should be closed and a new "Expand search functionality to enable boolean searches" issue should be created so we can clearly see what the goal is?

See: www.nypl.org/blog/2011/02/22/what-boolean-search for an explanation of what I mean by 'boolean search'

**Comment by AmandaPDSC** [comment]
A Boolean search would add some, but not all, of the functionality that we need. This particular issue relates to their being no way to find what is and isn't digitised - are you saying that a search on "NOT" with the blank box ticked for date digitised would produce these results?

Also, I'm not sure whether your comment on the advanced search being overwhelming is commenting on the difficulty of making all fields searchable from your perspective, or on searching from the user perspective. Only advanced users do these searches anyway, so I don't think the current advanced search format is an issue. The issue is really that we can't create search sets, and then add and subtract things to the set. Is there a way to do this without completely overhauling the way the data is stored and searched?

**Comment by LindaBarwick** [comment]
further to this, here is an actual use case

We have a collection that needs to have certain text appended to the comments field, but only for a subset of that collection. At present we have no way of doing so, thus we have to edit each record individually.

Linda

**Comment by AmandaPDSC** [comment]
Another thing which we would like to be able to do is to scroll through a list of search results using the next and previous buttons - currently if we view an item returned in a search and then click next, we get the next record in Nabu, not necessarily the next item from the most recent search.

**Comment by nthieberger** [comment]
Yes, querybuilder looks good

**Comment by agrimmtt** [comment]
Hi @nthieberger ,

This ticket, and related tickets #106 and #266 mentions a couple of related pieces of functionality.

1. Manipulating searches. For example, in the first comment of this ticket, Amanda referred to the ability to "invert searches, remove some items from a search, add two searches together etc".
2. Keeping a memory of the current search.
2.1. In the first comment of #106, Amanda talks about a button to return to search results.
2.2. In a comment made in September 2013 of ticket #106, Amanda refers to a desire to find the next result and previous result using the next and previous button, as opposed to merely navigating to the next and previous items in a collection.

Can you indicate which aspect is urgent?

**Comment by nthieberger** [comment]
I've summarised the key points here, all of which we'd like to have implemented please:
There is currently no way to search for items that have been digitised - so maybe I want to find all of the items in AC2 that are digitised (or all of those that aren't). We used to have a digitised yes/no tick box, but now there is only a date digitised field. To find any items with a date digitised we might need to have a wildcard search for that field (and others).
- ability to find 'not' something

- it would be great to be able to invert searches, remove some items from a search, add two searches together etc. Referenced in the thread for #106 

The issue is really that we can't create search sets, and then add and subtract things to the set. Is there a way to do this without completely overhauling the way the data is stored and searched?

We have a collection that needs to have certain text appended to the comments field, but only for a subset of that collection. At present we have no way of doing so, thus we have to edit each record individually.

Another thing which we would like to be able to do is to scroll through a list of search results using the next and previous buttons - currently if we view an item returned in a search and then click next, we get the next record in Nabu, not necessarily the next item from the most recent search.

Implement "javascript query builder ui": http://mistic100.github.io/jQuery-QueryBuilder/

**Comment by agrimmtt** [comment]
Hi @nthieberger ,

Thanks for summarizing this ticket. Can you order the different aspects of this ticket by their priority?

**Comment by nthieberger** [comment]
I've broken this out into separate issues #587, #588, #589
