### ISSUE TITLE
NABU strange behaviour

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#450]
Having had the spreadsheet import fail, I clicked on the 'items' button, and it downloaded a csv file ('search.csv') rather than returning to the items listing.

**Comment by nthieberger** [comment]
In fact, I can no longer get to the items page, it just downloads a file instead ...

**Comment by JonoGillett** [comment]
That's really odd, could you email me through the spreadsheet that you were trying to upload? I'll see if I can trace through the process.

**Comment by JonoGillett** [comment]
From looking into it, I feel like there's another issue at play here. The reason that you're getting a download is that the application is being told to produce a CSV - why, I don't yet know. I uploaded the invalid spreadsheet and got the error, but I never had the CSV download problem.
Some diagnostic questions:
- Have you changed browser, or installed any plugins that might be interfering?
- Does the same thing happen for the collections search tab?
- Does the same thing happen on staging as well?

As for the upload issue that was due to an empty countries field in the data - I didn't think that field was supposed to be required - the name was fine and it progressed through until it hit that later issue. I have gone through the uploader and added a number of checks to allow the sheet to be more flexible.

**Comment by nthieberger** [comment]
Have you changed browser, or installed any plugins that might be interfering?
No

Does the same thing happen for the collections search tab?
No it doesn't

Does the same thing happen on staging as well?
No, it doesn't do this on the staging server.

I have tried uploading the same file to both the production and staging servers but it fails.

**Comment by JonoGillett** [comment]
The spreadsheet upload fix is now deployed to staging. I'm still looking into the issue with the CSV, however I think you might be able to resolve it by clearing your cookies for catalog.paradisec.org.au and then trying again.

If you need any guidance on that, or it still doesn't work afterwards, let me know.

**Comment by nthieberger** [comment]
Yes, it sort of works. But it is an issue with how Excel formats numbers. Even though they are meant to be 'general' format, when they are not followed by an alphabetic character they get a decimal point and 0 added which fails the import see below. I have tried several different formatting options, but they don't seem to change Excel's mind about how it wants to present these identifiers.

SUCCESS: 15 items created/updated for collection AC1
Saved collection AC1, Arthur Capell recording collection
WARNING: item 112.0 invalid - skipped
WARNING: item 121.0 invalid - skipped
WARNING: item 125.0 invalid - skipped
WARNING: item 131.0 invalid - skipped
WARNING: item 201.0 invalid - skipped
WARNING: item 203.0 invalid - skipped
WARNING: item 204.0 invalid - skipped
WARNING: item 205.0 invalid - skipped
WARNING: item 206.0 invalid - skipped
WARNING: item 207.0 invalid - skipped
WARNING: item 208.0 invalid - skipped
WARNING: item 209.0 invalid - skipped
WARNING: item 212.0 invalid - skipped
WARNING: item 215.0 invalid - skipped
WARNING: item 217.0 invalid - skipped
WARNING: item 218.0 invalid - skipped
WARNING: item 220.0 invalid - skipped

**Comment by nthieberger** [comment]
Closing this for now in the hope that it doesn't happen next time a spreadsheet is uploaded
