### ISSUE TITLE
viewing .webm

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#459]
We need to be able to view .webm files (streaming html format). A test file is SN1-ZionaChurch20131128-Clip6.webm, but it is not visible in the viewer. Marco has reworked the viewer to deal with .webm, so it could be that NABU is not dealing with it properly? It does not appear in the listing in NABU, and it probably does not need to (there will be mp4 versions there) but it does need to be in the viewer.

**Comment by JonoGillett** [comment]
It looks like this was due to the old version of Ubuntu and various libraries in the server.

The version of 'avprobe' which is used to determine the essence metadata for audio/video files was too outdated to handle WEBM, and was thus failing when trying to upload them into NABU.

This was compounded due to the fact that Ubuntu 14.04 doesn't natively support ffmpeg which has a more up-to-date probe tool. I have installed ffmpeg via a slight workaround and aliased 'avprobe' to 'ffprobe' (they are 99% compatible, and we're not using any of the flags that are different).

I have now successfully uploaded the file you referenced and it is available in the list of essences, and also via the repository URL which the viewer uses:
http://catalog.paradisec.org.au/repository/SN1/ZionaChurch20131128/SN1-ZionaChurch20131128-Clip6.webm
