### ISSUE TITLE
Create citation form for essence files

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#474]
Create a new citation form and field for essence file metadata (adding the DOI and taking out the URL) : People/Role(s) ; Creation Date ; filetype; filename ; Access date;  DOI
Solomons Museum (collector), 1970; -, MPEG/X-WAV, SINM-OTP142-A.mp3  2015-10-13. DOI

**Comment by agrimmtt** [comment]
Should there be a comma between "SINM-OTP142-A.mp3" and "2015-10-13"?

**Comment by nthieberger** [comment]
yes,thanks

**Comment by agrimmtt** [comment]
http://144.6.225.96/collections/SINM/items/OTP142/essences/1039253 has a citation of

> Solomons Museum (collector), 1970; MPEG, SINM-OTP142-A.mp3, 2015-10-30.

It has "MPEG" rather than "-, MPEG/X-WAV". X-WAV must be the filetype of http://144.6.225.96/collections/SINM/items/OTP142/essences/1039254 , which has a citation of

> Solomons Museum (collector), 1970; X-WAV, SINM-OTP142-A.wav, 2015-10-30.

The only thing missing is the DOI, and that's because its DOI is blank. How does it look?
