### ISSUE TITLE
Find similar

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#509]
Can we add a button that puts the collector name and language name into a googlesearch?

**Comment by agrimmtt** [comment]
This is now available on the staging server.

http://144.6.225.96/collections/CI1 is an example of a collection linking to a search for the collector (no language, because collections don't have a single language), and http://144.6.225.96/collections/AB1/items/018 is an example of an item linking to a search for the collector and the language.

In the former, the matches are in red because Google does that when a search involves Chinese characters.

I chose to use a normal link rather than a button because of what happened last time buttons were used.
