### ISSUE TITLE
ID column doesn't sort (case sensitivity)

### ISSUE THREAD

**Issue by AmandaPDSC** [nabu-catalog/nabu#534]
related to #524 the ID column in item view also don't sort correctly. I've just been looking at CH3 and sorting by filename doesn't sort the CH3-09... items as I would expect

**Comment by agrimmtt** [comment]
What order are you getting, and what are you expecting?

**Comment by AmandaPDSC** [comment]
Capitalised letters are sorted before lower case letters instead of a simple alphabetical sort, so CH3-09Swadesh40W3 appears before CH3-09alphabetW1

**Comment by agrimmtt** [comment]
Sorting by case insensitive alphabetical order requires a little bit of extra work. Can you confirm that for now, it's only ID for collections and items that needs this? For example, that we don't yet need to be case insensitive when sorting by authors and languages, because we're currently unlikely to get this problem.

**Comment by agrimmtt** [comment]
BTW, don't worry about answering this quickly. I'm happy to work on other issues.

**Comment by AmandaPDSC** [comment]
Well I suppose it's much less likely that the language as given or collector fields will have lower case items, but I think a general principle should be that sorts are alphabetical, regardless of case. This is not the highest priority at the moment in any case.

**Comment by NickWardPDSC** [comment]
appears to be fixed. (Items in CH3-09... sort alphabetically regardless of case)
