### ISSUE TITLE
Viewer application should change thumbnail filename

### ISSUE THREAD

**Issue by agrimmtt** [nabu-catalog/nabu#572]
Currently, the viewer application asks for thumbnail filenames with a uppercase extension if the original file has an uppercase extension. Can you change the viewer so that for thumbnails, the extension is always in lowercase?

For example, if you go to http://catalog.paradisec.org.au/collections/SAW3/items/006 and go to the viewer page, the viewer application makes a request to `/repository/SAW3/006/SAW3-006-img01-thumb-PDSC_ADMIN.JPG`, because the original file is `SAW3-006-img01.JPG`. I'd like the viewer to make a request instead to `/repository/SAW3/006/SAW3-006-img01-thumb-PDSC_ADMIN.jpg`. That would mean I could get rid of a kludge in my code that "fixes" the extension of thumbnails.

**Comment by MLR-au** [comment]
Hi,

I'm the dev of the viewer app. The names I use for the resources come from the metadata feed:
http://catalog.paradisec.org.au/oai/item?verb=GetRecord&identifier=oai:paradisec.org.au:SAW3-006&metadataPrefix=olac

I understand why you're requesting me to change the case (which TBH is a trivial change to make) but then it introduces an artificial discrepancy between the names in the metadata feed and the things I actually request. If it's really important to you to make this change then I'd suggest that you change the case of the extension in the data feed which will then flow through to the viewer.

**Comment by agrimmtt** [comment]
Viewing the link you supplied me with doesn't mention `thumbnail` in any of the names. Can you send me the correct link?

**Comment by MLR-au** [comment]
Unfortunately there's a lot of information I have to construct from what's in that feed. The thumbnail urls is one of those. Given the name - and a known defined convention for naming thumbs - I massage the name into the right form.

**Comment by JonoGillett** [comment]
Hi @MLR-au,

I wonder if there might have been a misunderstanding, so let me have a go at explaining my thoughts.

- Thumbnails are always in jpg format, and always in lowercase. This is irrespective of the original file format (could be png, tif etc but still produces a jpg thumbnail) - this is the 'known defined convention'
- Thumbnails are (at the moment) solely used by the viewer, and as such have no real significance with respect to your concern about 'artificial' data in the viewer.
- We don't plan to include modifications to the data feed for thumbnail information, due to the fact that the feed needs to conform to a specification and has multiple consumers who won't have a need for thumbnails.

I took a look at the (minified) source of the viewer from Chrome and it looks like there's already code to add the '-thumb-PDSC_ADMIN' suffix, so all you'd need to do is change that line.

```
        d.thumbnails = _.map(d.images, function(a) {
            var b = a.split("/").pop()
            // just use "-thumb-PDSC_ADMIN.jpg"; on the following line
              , c = b.split(".")[0] + "-thumb-PDSC_ADMIN." + b.split(".")[1];
            return a.replace(b, c)
        }),
```

I hope that this clarifies our perspective. If you still have any issues with going ahead and implementing the change, I'm happy to chat further about it.

**Comment by MLR-au** [comment]
Hi Jono,

Sorry I missed this - stuffed up my notification settings.

Ok - to your points. I'm happy enough to change the suffix of the generated thumb urls to lowercase. I guess I was hoping that there would be consistency in naming between the original names (upper JPG) and thumbs (lower jpg). From my point of view it really makes no difference other than it's nice to be consistent solely because I have to derive so much extra data from that feed. The ideal case (for me) would be that I read the feed and pluck out all the things I need and just use them. Though as you rightly mention, the feed conforms to a spec so all the extra bits the viewer needs are unlikely to ever make it in.

How should we do this? I can easily make the change now and push out an update but then it'll be broken until you guys have updated your side. Or is that not an issue?

**Comment by agrimmtt** [comment]
It's ok for you to push it out, as it shouldn't break what we have.

**Comment by MLR-au** [comment]
Ok - I've just pushed a new version to the server and checked that all is working; which it is. 

I noticed that I was able to create folders so I went ahead and created a folder `production` and linked `current` to it. This relates to #576 so the viewer now loads from the production folder.

Would you be able to update the nginx server config as per my request in #576 so that I can deploy a new testing version of the viewer? See the notes in #576 for more info.

This ticket can be resolved now.

**Comment by agrimmtt** [comment]
Closing as per Marco's comment.
