### ISSUE TITLE
Create a DOI when an item is switched from private to public

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#594]
DOIs should not be generated for private items (as the DOI willn not be resolved) but will need to be generated when an item's status is changed.

**Comment by agrimmtt** [comment]
This will be fixed on the next deploy. In the meantime, I have turned off DOI minting so any new private objects won't have their DOIs minted.

**Comment by agrimmtt** [comment]
Are all essences treated as private? You have to be a logged-in user to be able to view any essences.

**Comment by nthieberger** [comment]
Andrew,

'Private' in our catalog is a category for metadata that is not published
to the web or to our feeds. Non-private information has varying conditions
of open-ness as specified in the access conditions field.

**Comment by agrimmtt** [comment]
Hi @nthieberger ,

Under what circumstances should an essence have a DOI minted, and under what circumstances should it not have a DOI minted?

**Comment by agrimmtt** [comment]
Minting DOIs for essences will occur as specified upon the next deployment.

**Comment by nthieberger** [comment]
There's an additional complication. We will deactivate DIs for the 63 collections that are private. If a collection is switched from private to public AND it has an existing DOI, then that DOI needs to be left alone and no new DOI should be minted. If, however, a private collection is created then no DOI should be minted. Any change in that collection to public would trigger the minting of a new DOI.

**Comment by agrimmtt** [comment]
@nthieberger The Rails application checks every day for any objects that ought to have a DOI minted but don't have one, and mints them.

The way it'd handle the scenarios you describe:

* Private collection that already has a DOI which becomes public: Ignored because it already has a DOI.
* New private collection that has no DOI: Ignored because it knows it should not have a DOI minted.
* Private collection with no DOI which becomes a public collection: Gets a DOI minted within one day of the change.

If you want to see the code, it's in `app/services/batch_doi_minting_service.rb`.

**Comment by nthieberger** [comment]
OK, sounds very good. Thanks.
