### ISSUE TITLE
RCSB1

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#598]
For some reason this item has duplicate files listed in NABU, but they are not in the collection. This suggests something strange in the way NABU is reading from this item, or maybe it is a relic of the previous multiple files in this item? http://catalog.paradisec.org.au/collections/RCSB1/items/ORIYA

**Comment by nthieberger** [comment]
Still not fixed. It seems to only be the listing of files in the item pane that is wrong, if you navigate from item to item it does not include duplicates.

**Comment by stasb** [comment]
@nthieberger There were duplicated items in this collection which I have removed. The reason that item-to-item navigation seemed to work is due to issue #596 , which I have fixed. Previously the item order was based on id when clicking 'next'. I have changed this ordering to be based on file name, as it is when viewing a collection, which fixes #596 .
