### ISSUE TITLE
adding a link next to each entry in the 'Country' field

### ISSUE THREAD

**Issue by enwardy** [nabu-catalog/nabu#609]
similar to the "See other information in this language" link next to each language in the 'Languages' field

**Comment by JonoGillett** [comment]
@enwardy @nthieberger I have updated Nabu staging to include links to language-archives.org for country as well as language. For example: http://144.6.225.96/collections/VKS/items/107_79

In order to avoid cluttering the UI, I have changed the country/language name to be a link itself and added a small explanatory note once rather than adding an extra link for every single line.
Please let me know if you prefer the previous approach, or would like any changes made.

**Comment by nthieberger** [comment]
This looks good, thanks.

**Comment by enwardy** [comment]
Yes that looks good. 

The example you have shown is on an Item, I assume it will be the same for the country and language labels at Collection level?

**Comment by juliamiller** [comment]
This does look much nicer!

Julia

**Comment by JonoGillett** [comment]
@enwardy Correct, both collection and item have been updated in the same way (country links added, link style changed) e.g. http://144.6.225.96/collections/VKS

**Comment by JonoGillett** [comment]
Released on 08/02/17
