### ISSUE TITLE
REST api

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#645]
Can you please let me know what is involved in creating a REST API to add to the two we already have? If it is not too much work, can we please get that added, and have the details put on the API page in NABU.

**Comment by j03w** [comment]
@nthieberger could you please clarify on what REST API are you referring to please? e.g. what resources you want to be exposed via the API and/or does it need to be conformed to a certain convention?

**Comment by nthieberger** [comment]
Hi, I do not know what would be the best kind of REST API to implement and
am ready to take your advice on this. The aim is to allow others to operate
on the data in the catalog and to create novel ways of visualising it, for
example.

**Comment by j03w** [comment]
interesting… let me get back to you

**Comment by j03w** [comment]
This might be a bit of a long shot but I think [GraphQL](http://graphql.org/) would be perfect enhancement for the collection of data.

GraphQL is a new standard/language to represent API in a way that easy for client/consumer of the API to discover and query for data. Client/consumer of the API will have control over what and how much of the data they want to pull out from the system.

GraphQL would also make it a bit simpler to implement new UI on top of the data compare to normal REST API.

**Comment by nthieberger** [comment]
Sure. But do we just use GraphQL to query our sql database, or is there an
interface that we can build that allows us (non-programmers!) to build our
own queries? The idea of the REST api is that it would allow any user to
create novel queries and visualisations of the data in NABU.

**Comment by j03w** [comment]
Rather than querying to the db we will create a schema describing types (resources in REST term) fields, operations and relationships. Users will be able to freely define their own _depth_ of graph.
Like [this for example](http://graphql.org/swapi-graphql/?query=%7B%0A%20%20allFilms%20%7B%0A%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20title%0A%20%20%20%20%20%20%20%20director%0A%20%20%20%20%20%20%20%20producers%0A%20%20%20%20%20%20%20%20releaseDate%0A%20%20%20%20%20%20%20%20characterConnection(first%3A%2010)%20%7B%0A%20%20%20%20%20%20%20%20%20%20pageInfo%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20startCursor%0A%20%20%20%20%20%20%20%20%20%20%20%20endCursor%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20gender%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20homeworld%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20species%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&operationName=null)

**Comment by nthieberger** [comment]
OK, and how much work would be involved in doing this? Will it allow us, for example, to send queries that provide our webpage with a real time update of collection size, number of files etc?

**Comment by j03w** [comment]
let me do fiddle around with it quickly and I'll get back to you on how much time it will take for us to develop that

**Comment by j03w** [comment]
so I've been fiddling around for a few hours and so far I have got a schema that looks like this:

```
type Collection {

}

type Country {
  arhive_link: String
  code: String
  id: ID!
  languages: Language
  name: String
  retired: Boolean
}

type Item {
  agents: [Person]
  citation: String
  collection: Collection
  collector: Person
  content_languages: [Language]
  countries: [Country]
  description: String
  full_identifier: String!
  id: ID!
  identifier: String!
  originated_on: String
  originated_on_narrative: String
  permalink: String!
  subject_languages: [Language]
  title: String
}

type Language {
  code: String
  countries: Country
  id: ID!
  name: String
}

type Person {
  collected_items: Item
  country: String
  first_name: String
  id: ID!
  last_name: String
}

type Query {
  items(limit: Int = 10, order: String = "id"): [Item]
}
```

Basically mean that if you send a query like this:

```
{
  items(limit: 2) {
    id
    title
    description
    identifier
    full_identifier
    countries {
      id
      name
    }
    subject_languages {
      id
      name
    }
    permalink
    citation
    collector {
      id
      first_name
      last_name
    }
  }
}
```

You'll get a response:

```
{
  "data": {
    "items": [
      {
        "id": "1",
        "title": "Pak Nongeng tells about the first four people, food taboos, and various other topics",
        "description": "Pak Nongeng tells about the first four people, food taboos, and various other topics",
        "identifier": "001",
        "full_identifier": "AA1-001",
        "countries": [
          {
            "id": "89",
            "name": "Indonesia"
          }
        ],
        "subject_languages": [
          {
            "id": "2975",
            "name": "Kendayan"
          }
        ],
        "permalink": "http://catalog.paradisec.org.au/collections/AA1/items/001",
        "citation": "Alexander Adelaar (collector), Alexander Adelaar (recorder), 1987; <i>Pak Nongeng tells about the first four people, food taboos, and various other topics</i>, X-WAV/MPEG,  2018-01-05. DOI: 10.4225/72/56E97A6DBA4F4",
        "collector": {
          "id": "58",
          "first_name": "Alexander",
          "last_name": "Adelaar"
        }
      },
      {
        "id": "2",
        "title": "Pak Kaslem tells: 2 folk stories + accounts of customary law",
        "description": "2 stories: Curità Mariam Ne' Baruk + Ne' Tanuk ba Ne' Ancong Leo --  Customary law accounts: the use of gold dust when one is defeated in battle, and rules when someone is cheating in battle",
        "identifier": "002",
        "full_identifier": "AA1-002",
        "countries": [
          {
            "id": "89",
            "name": "Indonesia"
          }
        ],
        "subject_languages": [
          {
            "id": "2975",
            "name": "Kendayan"
          }
        ],
        "permalink": "http://catalog.paradisec.org.au/collections/AA1/items/002",
        "citation": "Alexander Adelaar (collector), Alexander Adelaar (recorder), 1987; <i>Pak Kaslem tells: 2 folk stories + accounts of customary law</i>, MPEG/X-WAV,  2018-01-05. DOI: 10.4225/72/56E97A733DAE1",
        "collector": {
          "id": "58",
          "first_name": "Alexander",
          "last_name": "Adelaar"
        }
      }
    ]
  }
}
```

In summary, this is base on `Item` as a main resource/type, I haven't specified what will be in the `Collection` and haven't touched the `Essence` yet, but for basic stuff it's actually quite easy to do. We could iteratively add more feature to the API. I'll spend a bit more time on this and submit a PR for the first version so that at least we can have schema similar to this:
```
Item
|
| --> Collection |--> [Item]
|                         |--> [Country]
|                         |--> [Language]
|
| --> [Essence]
| --> [Person (Collector)]
| --> [Country]
| --> [Language]
...
```

Note that it is also possible to replicate *all* of the search facets through GraphQL schema but that will take sometime as there's no library to easily convert/map GraphQL to Solr query, even though the field/facet could be mapped 1-to-1 it will still need to be manually mapped out in the code.

**Comment by j03w** [comment]
Pull request submitted #650

**Comment by nthieberger** [comment]
Thanks. I'm not sure how this would be used, would we provide a page (on our website or in the API page of NABU) outlining the terms to use for queries? And is there a need for resumption tokens for large search results?

**Comment by j03w** [comment]
@nthieberger the library that we use come with an IDE where anyone can use to play around with the API.

For pagination just require number of page and limit number of item per page.

**Comment by nthieberger** [comment]
OK thanks. Would you be able to write a summary of the functionality of this that can then be put on our API page (http://catalog.paradisec.org.au/apidoc)?

**Comment by JonoGillett** [comment]
Estimate here only includes adding documentation

**Comment by agrimmtt** [comment]
@nthieberger Is it ok to close this ticket?

**Comment by tom-h** [comment]
This is a really nice addition to the catalogue. And could be the cornerstone to building a new or refreshed catalogue at some point in the future.

Obviously, this is a late request, but it would be good to add more fields to query. At the very least it would be good to return collections and essences (rather than items in collections, or essences in items). But I think it would also be useful to be able to query several other fields modelled as Types in the schema: languages, countries, data_types,  etc... pretty much all of them.

I'd also suggest that unless authentication was possible, {item{private}} is pretty much redundant.

**Comment by agrimmtt** [comment]
@tom-h Who is this comment addressed to?

**Comment by tom-h** [comment]
Apologies @agrimmtt, this is addressed to @nthieberger from the perspective of a consumer of the API (from someone not from PARADISEC).
