### ISSUE TITLE
Random checksumming needed on whole collection

### ISSUE THREAD

**Issue by AmandaPDSC** [nabu-catalog/nabu#653]
we should do checksumming on the whole collection every now and then to ensure its integrity - maybe once a month (or staged checks on part of the collection every week)?

**Comment by nthieberger** [comment]
Can this be done regularly, maybe it can do chunks at a time so that we know it has checked the whole collection every three months? And also have a button in the dashboard to allow us to run it over the collection.

**Comment by JonoGillett** [comment]
@nthieberger regarding the 'dashboard button' what is the goal there? Do you want to be able to check a single collection (i.e. AA1)? or is 'the collection' referring to the catalog instead?

If you're talking about the whole catalog, then that seems at odds with the desire to run over a small chunk at a time across the course of 3 months.

**Comment by enwardy** [comment]
hi @JonoGillett , thanks this periodic checking is working well, sending a report each day (except Sunday).

I'm curious as to why it commenced with collection ALB01, and onwards from there. So it seems to have skipped over AA1..to..AL1 (the first 15 collections). Just bringing this to your attention. I guess they will be covered in the next pass when it comes in a couple of months time.

**Comment by enwardy** [comment]
Another query: BJM01-001-01.wav checksum failed, however I checked it and it does seem to match, see image attached. As this file is 4GB, I'm guessing this might be because of a file size limit on the utility that generates and/or checks the checksums. 
Either within Nabu, or in the script that produces these "validating checksums for [....collections...]" reports?  
![bjm-001-01wav-checksum_match](https://user-images.githubusercontent.com/2100477/42354507-a478c70a-810a-11e8-8cd8-a702ae7224ce.jpeg)

**Comment by nthieberger** [comment]
Yes, it does look like the size limit may be the problem here. So the
checksum is fine.
Thanks,
Nick

**Comment by agrimmtt** [comment]
@AmandaPDSC @nthieberger Is there anything left to do on this issue?

**Comment by enwardy** [comment]
@agrimmtt I have been monitoring the reports, and looking into the failed checksums as they come up. It looks to me like the process is working well, highlighting issues in the checksums, most of which I have been able to fix. 

For now i think this issue could be considered closed, unless @nthieberger thinks otherwise?

**Comment by enwardy** [comment]
yes, the process is (and will be) ongoing.
