### ISSUE TITLE
Action needed when a checksum fails

### ISSUE THREAD

**Issue by AmandaPDSC** [nabu-catalog/nabu#654]
We have found that some of the checksum messages that report a checksum failure, upon investigating the problem, the file in Nabu appears perfectly ok. We often get a checksum fail message followed by a successfully copied to archive message.
Is it possible that the failure is due to the checksum report being generated at the time that the file is being copied and saved?
Could a second checksum check be run (if file has failed to open), or alternatively the file be moved into rejected? 

Some recent examples related to the above comment:

8 February 2018 at 13:02
files that failed the checksum:
/srv/catalog/MH2/MELANDAI4/MH2-MELANDAI4-B.wav: FAILED

3 February 2018 at 04:00
files that failed the checksum:
/srv/catalog/MH2/B_ADAT5/MH2-B_ADAT5-B.wav: FAILED open or read

**Comment by JonoGillett** [comment]
This change has now been deployed into production. The new behaviour is listed below.

Please let me know if you have any questions or comments.

**Checksum validation steps**
1. Before the files themselves are checked, any checksum files are first processed
1. A summary line indicating how many checksum files are found will be printed
   * e.g. `[CHECKSUM] Found 2 checksum files (out of a total of 4 files)`
   * this line indicates that 4 files were found in the import directory, of which 2 were checksums not essences
1. if the checksum file couldn't be read, or was invalid itself, a general error will be reported
   * `[CHECKSUM] error while reading the checksum file XX1-001-checksum-PDSC_ADMIN.txt, unable to check if sums are valid: <some error reason goes here>`
1. If any checksums fail, the associated essence file will not be imported
1. A summary line indicating how many checksums were checked, and any failures will be printed
   * e.g. `[CHECKSUM] Checked 7 essence checksums in 2 files. 5 passed | 2 failed`
   * Note here that a single checksum file can contain multiple sums (e.g. for all essences in a single file)
1. If there were failures, then any failed files will be printed, including the md5sum error message
   * e.g.
    ```
    [CHECKSUM] Files that failed the checksum check:
    [CHECKSUM] - /srv/nabu/archive_me/XX1-001-A.mp3: FAILED open or read
    [CHECKSUM] - /srv/nabu/archive_me/XX1-001-B.mp3: FAILED
    ```
   * this would indicate (potentially) that XX1-001-A.mp3 didn't exist in the import directory, and that XX1-001-B.mp3 was corrupt because the hash check failed

Once the checksum process has completed, the normal file import process begins
1. This will print checksum failure message e.g. `ERROR: file XX1-001-A.mp3 skipped, since it failed the checksum validation`
1. A and B would then be moved to Rejected, along with the checksum file (to allow manual checking and re-processing)

Any files which pass checks in the same file will be moved to the archive as normal.

**Comment by enwardy** [comment]
thanks @JonoGillett looks good.

just one query I have: the report seems to always list twice the number of 'files' that it summarises at the top. For example, the below report says "Checked 8 essence checksums in 4 files", but then you look down the list of files processed and it is 8, not 4.

[CHECKSUM] Found 4 checksums files (out of a total of 12 files) ...
[CHECKSUM] Checked 8 essence checksums in 4 files. 8 passed | 0 failed
Start processing files to import...

INFO: Inspecting file LSNG04-019-01.wav...
INFO: essence LSNG04-019-01.wav metadata imported into Nabu. The file will now be moved...
SUCCESS: file LSNG04-019-01.wav copied into archive at /srv/catalog/LSNG04/019/
...done

SUCCESS: file LSNG04-019-01-checksum-PDSC_ADMIN.txt copied into archive at /srv/catalog/LSNG04/019/
...done

INFO: Inspecting file LSNG04-025-02.mp3...
INFO: essence LSNG04-025-02.mp3 metadata imported into Nabu. The file will now be moved...
SUCCESS: file LSNG04-025-02.mp3 copied into archive at /srv/catalog/LSNG04/025/
...done

INFO: Inspecting file LSNG04-019-01.mp3...
INFO: essence LSNG04-019-01.mp3 metadata imported into Nabu. The file will now be moved...
SUCCESS: file LSNG04-019-01.mp3 copied into archive at /srv/catalog/LSNG04/019/
...done

INFO: Inspecting file LSNG04-026-01.mp3...
INFO: essence LSNG04-026-01.mp3 metadata imported into Nabu. The file will now be moved...
SUCCESS: file LSNG04-026-01.mp3 copied into archive at /srv/catalog/LSNG04/026/
...done

SUCCESS: file LSNG04-025-02-checksum-PDSC_ADMIN.txt copied into archive at /srv/catalog/LSNG04/025/
...done

INFO: Inspecting file LSNG04-026-02.wav...
INFO: essence LSNG04-026-02.wav metadata imported into Nabu. The file will now be moved...
SUCCESS: file LSNG04-026-02.wav copied into archive at /srv/catalog/LSNG04/026/
...done

SUCCESS: file LSNG04-026-01-checksum-PDSC_ADMIN.txt copied into archive at /srv/catalog/LSNG04/026/
...done

INFO: Inspecting file LSNG04-026-01.wav...
INFO: essence LSNG04-026-01.wav metadata imported into Nabu. The file will now be moved...
SUCCESS: file LSNG04-026-01.wav copied into archive at /srv/catalog/LSNG04/026/
...done

INFO: Inspecting file LSNG04-025-02.wav...
INFO: essence LSNG04-025-02.wav metadata imported into Nabu. The file will now be moved...
SUCCESS: file LSNG04-025-02.wav copied into archive at /srv/catalog/LSNG04/025/
...done

SUCCESS: file LSNG04-026-02-checksum-PDSC_ADMIN.txt copied into archive at /srv/catalog/LSNG04/026/
...done

INFO: Inspecting file LSNG04-026-02.mp3...
INFO: essence LSNG04-026-02.mp3 metadata imported into Nabu. The file will now be moved...
SUCCESS: file LSNG04-026-02.mp3 copied into archive at /srv/catalog/LSNG04/026/
...done

**Comment by JonoGillett** [comment]
@enwardy this 'discrepancy' is due to the fact that each checksum file contains one (or more) checksum hashes. I've included below an explanation, let me know if that doesn't help and we can maybe change the logging to be clearer.

- Essence file
  - An essence file is the usual media file or document that is being imported into Nabu.
- Checksum file
  - A checksum file is an admin file (a TXT file) containing one or more checksums which relate to essence files. e.g.
  ```
    97agsd97asgd9 AA1-001-A.mp3
    98shdf98sdf98h AA1-001-A.wav
   ```
- checksum
  - A checksum is the hash of a single essence file (e.g. `97agsd97asgd9 AA1-001-A.mp3`).

The reason the count is usually double the number of files is that the checksum file typically contains both the mp3 and the wav file checksum.

The example above with 4 checksum files, containing 8 checksums will result in:
- 8 essence files being imported
- plus an additional 4 admin files (the checksum files)
- for a total of 12 files

**Comment by enwardy** [comment]
@JonoGillett thanks for that explanation, i think i get it :)

**Comment by enwardy** [comment]
@JonoGillett some strange behaviour in the reports, hoping you can provide some explanation:

On several occasions recently we've had a FAILED checksum reported, but then upon looking close I have found that the file had PASSED SUCCESSFULLY in an _EARLIER_  report.

E.g.

- CLC-JGA_HIST_20100330-1.wav:

 SUCCESS (Report: Tue 15-May, 4:04 PM)
then...
FAILED (Report: Tue 15-May, 5:28 PM) 

- CLC-JGA_HIST_20100413_4-8.wav , CLC-JGA_HIST_20100413_4-8.mp3, and CLC-JGA_HIST_20100417-1.mp3 , all three SUCCESS (Report: Tue 15-May 5:28pm) ...and then FAILED 30 minutes later (Report: Tue 15-May 6:05pm).

The files all look fine in NABU, so it seems to be just an error in the reporting, what do you think?

**Comment by agrimmtt** [comment]
@enwardy Can you forward me all emails mentioning CLC-JGA_HIST_20100330-1.wav ?

**Comment by enwardy** [comment]
@agrimmtt I have just forwarded you the two checksum emails - passed and then failed

**Comment by enwardy** [comment]
further regarding my most recent comments above (22 May), I think I have figured out what is causing this. Explained here: https://github.com/nabu-catalog/nabu/issues/675
