### ISSUE TITLE
Search for collection not working

### ISSUE THREAD

**Issue by jodiekell** [nabu-catalog/nabu#685]
Tuesday 18th June at approx 11am searched for AM4 in a collection search. It went through to page "something went wrong".
We could access the collection by going to one item and using the link back into the collection

**Comment by nthieberger** [comment]
Maybe the NABU database needs a restart?

**Comment by AmandaPDSC** [comment]
I've talked this through with Murray-Luke and it seems that the collector for this collection was deleted as a user (Anna Margetts). I'm not sure why this would have been done. Because the collector is a mandatory field on a collection page, this is causing the page to fail to load. I will look at this with Prash when he's back in the office.

**Comment by prash01** [comment]
When i try to upload a metadata spreadsheet for AM4 i'm getting "Collection AM4 exists but with different collector Anna Margetts - please fix spreadsheet". I've tried to add Anna Margetts user id (5546) as a collector and i'm getting "The page you were looking for doesn't exist." @mpeard

**Comment by AmandaPDSC** [comment]
@mpeard are you able to add Anna Margetts back in as collector? we don't seem to be able to do it

**Comment by LindaBarwick** [comment]
Yes I get a "something went wrong" message whenever I try to edit the collection to add her

**Comment by AmandaPDSC** [comment]
Murray-Luke has changed the user ID for Anna Margetts to the original user ID number and this has solved the problem. I'm closing this issue and opening another one to make it impossible to delete a user that is also a collector
