### ISSUE TITLE
changing email addresses

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#692]
We are currently unable to change primary addresses, but we need to. Can that please be a new feature in NABU

**Comment by johnf** [comment]
@nthieberger Users can now change their email address when they click on their name top right?

Do you also want to be able to change email address in the admin section? 

Also is his for users or contacts?

**Comment by nthieberger** [comment]
yes, we should also be able to do this if a user is unable to. For anyone with an email address

**Comment by johnf** [comment]
OK This now works.

If a user changes it themselves, they will receive an email asking them to confirm they have access to the new email address.
Once they confirm it they can then login with the new email address.

The same thing happens if an admin changes it. (If this is not what we want I can try to work around the default functionality for admins)
