### ISSUE TITLE
image files aren't being shown

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#704]
e.g. https://catalog.paradisec.org.au/collections/NT1/items/98010/essences/1010798

and the same file in the viewer:
https://catalog.paradisec.org.au/viewer/#/NT1/98010/images/NT1-98010-001.jpg

**Comment by johnf** [comment]
Reopening as something is still afoot with NFS server

**Comment by johnf** [comment]
OK solved this one.

I think the underlying NFS issues are fixed with the noresvport setting that Intersect suggested.

The issue here and why the catalog was crashing is that, if a file hasn't been accessed in a while, the catalog NFS needs to pull it from tape. This could take a minute.

This was hanging the rails puma process as we only have 5 threads. So if the user keeps hitting download we use up the rails threads.

I've now offloaded this to ngin how has 1000 of threads available

**Comment by nthieberger** [comment]
sounds plausible, thanks!
