### ISSUE TITLE
Google result for PARADISEC catalog

### ISSUE THREAD

**Issue by NickWardPDSC** [nabu-catalog/nabu#709]
Google result shows the catalog and then underneath that

"No information is available for this page."

**Comment by johnf** [comment]
So back in 2012 we restricted the entire site so that web crawlers can't crawl it.

I noticed this the other day and was going to raise it.

Is there any reason we wouldn't want web crawlers to index the site?

/cc @nthieberger

**Comment by AmandaPDSC** [comment]
We wouldn’t want private collections exposed. But they are only visible with an admin login. I don’t see any reason otherwise

On 18 Mar 2023, at 9:21 pm, John Ferlito ***@***.***> wrote:

﻿

So back in 2012 we restricted the entire site so that web crawlers can't crawl it.

I noticed this the other day and was going to raise it.

Is there any reason we wouldn't want web crawlers to index the site?

/cc @nthieberger<https://github.com/nthieberger>

**Comment by nthieberger** [comment]
Yes, if those collections are not visible to crawlers it's ok. I think
google gets our api anyway, maybe once it is in OLAC, but the more the
merrier.

**Comment by johnf** [comment]
I've updated the robots.txt, will check in a few days if Google ishitting the logs

**Comment by johnf** [comment]
@nthieberger in the OAI feeds we use URLs like https://catalog.paradisec.org.au/repository/TD1/P00278
which then redirects to https://catalog.paradisec.org.au/collections/TD1/items/P00278.

Do you know why we do this, and which if those two URLs do you want google to index? I would suggest the latter as it will be faster for the user (i.e. no redirect)

**Comment by nthieberger** [comment]
ok, we can try without redirects, thanks

**Comment by johnf** [comment]
same for collection and essence

**Comment by johnf** [comment]
I've kicked off a recrawl google
