### ISSUE TITLE
item search not working

### ISSUE THREAD

**Issue by nthieberger** [nabu-catalog/nabu#710]
Searching for this: AC1-243 in the items search gives 255 results, not just the item it should be showing.

**Comment by johnf** [comment]
@nthieberger If you search for it in quote e.g. `"AC1-243"` it returns just the one record.

Is that OK or would you prefer the quotes aren't needed.

**Comment by johnf** [comment]
@nthieberger building from that, if the search term matches an item, should it also redirect straight to the page for that item to save the user a click?

**Comment by nthieberger** [comment]
No I don't think that's necessary. And usually a search returns a number of
hits.

**Comment by johnf** [comment]
OK worked this out, default had changed between old and new solar versions

**Comment by nthieberger** [comment]
But there's still strange behaviour in the search, e.g.,
https://catalog.paradisec.org.au/items/search?search=ac1-145 returns item
AC1-428 ( there is no item AC1-145) instead of no hits. But this item has
the string 145 in the notes field. So, the search is not looking for the
literal string in the search box but for any bits of it.

A search for https://catalog.paradisec.org.au/items/search?search=ac1-140
returns no hits

**Comment by johnf** [comment]
This is a bit tricky (search engines are complicated beasts).

Can I suggest to simplify we use the following logic
* Check directly if the string matches an identifier in the database.
* If it does redirect to the page for that item e.g. /collections/AC1/items/101
* Otherwise return search results

The latest version of solar is working differently to the old one and I don't think I'll be able to make it do exactly what you want.
There is no way to get it to understand that the identifier is special and that it should be returned as a single result. It's doing its best to return anything that looks like a match.

The best I could do is make sure that it's always the first result but then the order of results would be based on how well the search matches.
Currently we sort by the identifier by default

**Comment by nthieberger** [comment]
Yes, sure , whatever works best, and we can get used to it.
